FROM nginx:1.22.1
COPY nginx.conf /etc/nginx/templates/default.conf.template


# sudo nginx -t  Расположение конфига из теории ЯП
# nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
# nginx: configuration file /etc/nginx/nginx.conf test is successful
  # COPY nginx.conf /etc/nginx/nginx.conf - базовый файл конфигурации