name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report -m

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CRM-for-Yandex-ambassadors/backend
